// ── Auth server functions ──
import { compare, hash as hashPassword } from "bcryptjs";
import { createServerFn } from "@tanstack/react-start";
import { deleteCookie, getCookie, setCookie } from "@tanstack/react-start/server";
import { getDb, createSession, createUser, deleteSession, deleteExpiredSessions, getPasswordHash, createPasswordResetToken, consumePasswordResetToken, updatePasswordHash, getSessionByToken, getUserByEmail, getUserById, getProfileCount, incrementInterviewCount, getUserLimits, recordPurchase, listEntitlements, getOwnerMetrics as queryOwnerMetrics, getPendingDraftTransfer, executeDraftTransfer } from "~/db";
import { claimFoundingBetaReservation } from "~/lib/founding-beta";
import { sendPasswordResetEmail, sendWelcomeEmail } from "~/email";
import { compileInterviewMarkdown } from "./-meosCompiler";
import { getMeosGraph } from "./-meosGraph";

const SESSION_COOKIE = "alvira_session";
const SESSION_MAX_AGE = 30 * 24 * 60 * 60;
function sessionCookieOptions() { const domain = process.env.ALVIRA_SESSION_COOKIE_DOMAIN?.trim(); return { path: "/", maxAge: SESSION_MAX_AGE, httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax" as const, ...(domain ? { domain } : {}) }; }
function setSessionCookie(token: string): void { setCookie(SESSION_COOKIE, token, sessionCookieOptions()); }
function getSessionTokenFromRequest(): string | null { try { return getCookie(SESSION_COOKIE) ?? null; } catch { return null; } }
function isOwnerUser(user: { email: string }): boolean { const ownerEmail = (process.env.ALVIRA_OWNER_EMAIL ?? "tahlia.ashwood@gmail.com").trim().toLowerCase(); return user.email.trim().toLowerCase() === ownerEmail; }
const TEST_ACCESS_COOKIE = "alvira_test_access";
type TestAccessMode = "actual" | "founder" | "free" | "pro" | "lifetime";
const TEST_ACCESS_EMAILS = new Set(["codex-smoke-1786676512909@example.com", "alvira@agentmail.to"]);
function isAccessTestUser(user: { email: string }): boolean { return isOwnerUser(user) || TEST_ACCESS_EMAILS.has(user.email.trim().toLowerCase()); }
function testAccessCookieOptions() { const domain = process.env.ALVIRA_SESSION_COOKIE_DOMAIN?.trim(); return { path: "/", maxAge: SESSION_MAX_AGE, httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax" as const, ...(domain ? { domain } : {}) }; }
function getTestAccessMode(user: { email: string }): TestAccessMode | null { if (!isAccessTestUser(user)) return null; let raw: string | null = null; try { raw = getCookie(TEST_ACCESS_COOKIE) ?? null; } catch {} if (raw === "actual" || raw === "founder" || raw === "free" || raw === "pro" || raw === "lifetime") return raw; return isOwnerUser(user) ? "founder" : "actual"; }
function getEffectiveTier(user: { email: string; tier: string }): string { const mode = getTestAccessMode(user); return mode === "free" || mode === "pro" || mode === "lifetime" ? mode : user.tier; }
function hasFounderAccess(user: { email: string }): boolean { return getTestAccessMode(user) === "founder"; }

export const signup = createServerFn({ method: "POST" }).validator((data: unknown) => { const d = data as { email?: string; password?: string }; if (!d.email || typeof d.email !== "string" || !d.email.includes("@")) throw new Error("A valid email is required."); if (!d.password || typeof d.password !== "string" || d.password.length < 8) throw new Error("Password must be at least 8 characters."); return { email: d.email.trim().toLowerCase(), password: d.password }; }).handler(async ({ data }) => { const existing = await getUserByEmail(data.email); if (existing) throw new Error("An account with this email already exists."); const passwordHash = await hashPassword(data.password, 10); const userId = crypto.randomUUID(); let user = await createUser(userId, data.email, passwordHash); await claimFoundingBetaReservation(user); user = (await getUserById(userId))!; await sendWelcomeEmail(data.email); const token = crypto.randomUUID(); const expiresAt = new Date(Date.now() + SESSION_MAX_AGE * 1000).toISOString(); await createSession(userId, token, expiresAt); setSessionCookie(token); const pendingTransfer = await getPendingDraftTransfer(data.email); if (pendingTransfer) await executeDraftTransfer(pendingTransfer.id, userId); return { user: { id: user.id, email: user.email, tier: user.tier }, expiresAt }; });

export const login = createServerFn({ method: "POST" }).validator((data: unknown) => { const d = data as { email?: string; password?: string }; if (!d.email || typeof d.email !== "string" || !d.email.includes("@")) throw new Error("A valid email is required."); if (!d.password || typeof d.password !== "string") throw new Error("Password is required."); return { email: d.email.trim().toLowerCase(), password: d.password }; }).handler(async ({ data }) => { const hash = await getPasswordHash(data.email); if (!hash) throw new Error("Invalid email or password."); const valid = await compare(data.password, hash); if (!valid) throw new Error("Invalid email or password."); const user = (await getUserByEmail(data.email))!; const token = crypto.randomUUID(); const expiresAt = new Date(Date.now() + SESSION_MAX_AGE * 1000).toISOString(); await createSession(user.id, token, expiresAt); setSessionCookie(token); return { user: { id: user.id, email: user.email, tier: user.tier }, expiresAt }; });

const RESET_TOKEN_MAX_AGE = 60 * 60 * 1000;
const PUBLIC_SITE_URL = process.env.PUBLIC_SITE_URL || "https://alviratech.vercel.app";
export const requestPasswordReset = createServerFn({ method: "POST" }).validator((data: unknown) => { const email = (data as { email?: string }).email; if (!email || typeof email !== "string" || !email.includes("@")) throw new Error("A valid email is required."); return email.trim().toLowerCase(); }).handler(async ({ data }) => { const user = await getUserByEmail(data); if (user) { const token = crypto.randomUUID(); await createPasswordResetToken(user.id, token, new Date(Date.now() + RESET_TOKEN_MAX_AGE).toISOString()); await sendPasswordResetEmail(user.email, `${PUBLIC_SITE_URL}/reset-password?token=${encodeURIComponent(token)}`); } return { success: true }; });

export const resetPassword = createServerFn({ method: "POST" }).validator((data: unknown) => { const d = data as { token?: string; newPassword?: string }; if (!d.token || typeof d.token !== "string") throw new Error("Reset token is required."); if (!d.newPassword || typeof d.newPassword !== "string" || d.newPassword.length < 8) throw new Error("Password must be at least 8 characters."); return { token: d.token, newPassword: d.newPassword }; }).handler(async ({ data }) => {
  const userId = await consumePasswordResetToken(data.token);
  if (!userId) throw new Error("This reset link is invalid or has expired. Please request a new one.");
  const passwordHash = await hashPassword(data.newPassword, 10);
  const updated = await updatePasswordHash(userId, passwordHash);
  if (!updated) throw new Error("We could not save your new password. Please request a new reset link and try again.");
  const persistedHash = await getPasswordHash((await getUserById(userId))?.email ?? "");
  if (!persistedHash || persistedHash !== passwordHash) throw new Error("We could not verify your new password was saved. Please request a new reset link and try again.");
  const valid = await compare(data.newPassword, persistedHash);
  if (!valid) throw new Error("We could not verify your new password. Please request a new reset link and try again.");
  return { success: true };
});

export const logout = createServerFn({ method: "POST" }).handler(async () => { const token = getSessionTokenFromRequest(); if (token) await deleteSession(token); try { deleteCookie(SESSION_COOKIE, sessionCookieOptions()); deleteCookie(TEST_ACCESS_COOKIE, testAccessCookieOptions()); } catch {} return { success: true }; });

async function requireUser() { const token = getSessionTokenFromRequest(); if (!token) throw new Error("Authentication required."); const session = await getSessionByToken(token); if (!session || new Date(session.expires_at) < new Date()) throw new Error("Authentication required."); const user = await getUserById(session.user_id); if (!user) throw new Error("Authentication required."); return user; }

export const claimPurchase = createServerFn({ method: "POST" }).validator((data: unknown) => { const product = (data as { product?: string }).product; if (product !== "meos_build" && product !== "meos_care") throw new Error("Unsupported purchase."); return { product }; }).handler(async ({ data }) => { const user = await requireUser(); await recordPurchase(user.id, data.product); return { success: true }; });
export const getEntitlements = createServerFn({ method: "GET" }).handler(async () => { const user = await requireUser(); const entitlements = await listEntitlements(user.id); if (hasFounderAccess(user) && !entitlements.includes("meos_build")) entitlements.push("meos_build"); return entitlements; });
export const authorizeMeos = createServerFn({ method: "GET" }).handler(async () => { const user = await requireUser(); if (hasFounderAccess(user)) return { authorized: true }; const { requireMeos } = await import("./-entitlements.server"); await requireMeos(user); return { authorized: true }; });

export const saveProfile = createServerFn({ method: "POST" }).validator((data: unknown) => { const d = data as { topic?: string; tier?: string; state?: unknown; portrait?: unknown; offering?: string; preview?: boolean }; if (!d.topic || typeof d.topic !== "string" || !d.tier || !d.state) throw new Error("Topic, tier, and state are required."); return { topic: d.topic.trim(), tier: d.tier, state: d.state, portrait: d.portrait, preview: d.preview === true, offering: d.offering === "meos" ? "meos" as const : "context" as const }; }).handler(async ({ data }) => { const user = await requireUser(); const founderAccess = hasFounderAccess(user); const effectiveTier = getEffectiveTier(user); if (data.offering === "meos" && !data.preview && !founderAccess) { const { requireMeos } = await import("./-entitlements.server"); await requireMeos(user); } const d = getDb(); const existing = (await d.query("SELECT id FROM profiles WHERE user_id = $1 AND topic = $2", [user.id, data.topic]))[0] as { id: string } | undefined; if (!founderAccess && effectiveTier === "free" && !existing) { const count = await getProfileCount(user.id); if (count >= 1) return { error: "limit_reached", limit: "profiles" }; } const id = existing?.id ?? crypto.randomUUID(); await d.query(existing ? "UPDATE profiles SET offering = $1, tier = $2, state_json = $3, portrait_json = COALESCE($4, portrait_json), updated_at = NOW() WHERE id = $5 AND user_id = $6" : "INSERT INTO profiles (id, user_id, topic, offering, tier, state_json, portrait_json) VALUES ($1, $2, $3, $4, $5, $6, $7)", existing ? [data.offering, data.tier, JSON.stringify(data.state), data.portrait ? JSON.stringify(data.portrait) : null, id, user.id] : [id, user.id, data.topic, data.offering, data.tier, JSON.stringify(data.state), data.portrait ? JSON.stringify(data.portrait) : null]); return { id }; });
export const listProfiles = createServerFn({ method: "GET" }).handler(async () => { const user = await requireUser(); return getDb().query("SELECT id, topic, offering, tier, updated_at FROM profiles WHERE user_id = $1 ORDER BY updated_at DESC", [user.id]); });
export const getMeosProfiles = createServerFn({ method: "GET" }).handler(async () => { const user = await requireUser(); const rows = await getDb().query("SELECT id, topic, tier, state_json, portrait_json, updated_at FROM profiles WHERE user_id = $1 AND offering = 'meos' ORDER BY updated_at DESC", [user.id]) as Array<{ id: string; topic: string; tier: string; state_json: string; portrait_json: string | null; updated_at: string }>; return rows.map(row => ({ ...row, state: JSON.parse(row.state_json), portrait: row.portrait_json ? JSON.parse(row.portrait_json) : null })); });
export const saveMeosPortrait = createServerFn({ method: "POST" }).validator((data: unknown) => ({ profileId: String((data as { profileId?: string }).profileId ?? ""), portrait: (data as { portrait?: unknown }).portrait })).handler(async ({ data }) => { const user = await requireUser(); await getDb().query("UPDATE profiles SET portrait_json = $1, offering = 'meos', updated_at = NOW() WHERE id = $2 AND user_id = $3", [JSON.stringify(data.portrait), data.profileId, user.id]); return { success: true }; });
export const loadProfile = createServerFn({ method: "POST" }).validator((data: unknown) => ({ profileId: String((data as { profileId?: string }).profileId ?? "") })).handler(async ({ data }) => { const user = await requireUser(); const row = (await getDb().query("SELECT id, topic, offering, tier, state_json FROM profiles WHERE id = $1 AND user_id = $2", [data.profileId, user.id]))[0] as { id: string; topic: string; offering: string; tier: string; state_json: string } | undefined; if (!row) throw new Error("Profile not found."); return { id: row.id, topic: row.topic, offering: row.offering, tier: row.tier, state: JSON.parse(row.state_json) }; });
export const deleteProfile = createServerFn({ method: "POST" }).validator((data: unknown) => ({ profileId: String((data as { profileId?: string }).profileId ?? "") })).handler(async ({ data }) => { const user = await requireUser(); await getDb().query("DELETE FROM profiles WHERE id = $1 AND user_id = $2", [data.profileId, user.id]); return { success: true }; });
export const autosaveInterview = createServerFn({ method: "POST" }).validator((data: unknown) => { const d = data as { offering?: string; topic?: string; state?: unknown }; if (!d.offering || !d.topic || !d.state) throw new Error("Interview state is required."); return { offering: d.offering.trim(), topic: d.topic.trim(), state: d.state }; }).handler(async ({ data }) => { const user = await requireUser(); await getDb().query("INSERT INTO interview_drafts (user_id, offering, topic, state_json, updated_at) VALUES ($1, $2, $3, $4, NOW()) ON CONFLICT(user_id, offering) DO UPDATE SET topic=excluded.topic, state_json=excluded.state_json, updated_at=NOW()", [user.id, data.offering, data.topic, JSON.stringify(data.state)]); return { success: true }; });
export const finalizeInterviewDraft = createServerFn({ method: "POST" }).validator((data: unknown) => ({ topic: typeof (data as { topic?: string }).topic === "string" ? (data as { topic?: string }).topic!.trim() : "" })).handler(async ({ data }) => { const user = await requireUser(); const row = (await getDb().query(`SELECT offering, topic, state_json FROM interview_drafts WHERE user_id = $1 AND NOT EXISTS (SELECT 1 FROM draft_transfers t WHERE t.source_user_id = $1 AND t.source_offering = interview_drafts.offering) ORDER BY updated_at DESC LIMIT 1`, [user.id]))[0] as { offering: string; topic: string; state_json: string } | undefined; if (!row) throw new Error("No interview in progress to save."); const state = JSON.parse(row.state_json) as { domains?: Record<string, { answers?: string[] }> }; const topic = data.topic || row.topic || "My Profile"; const existing = (await getDb().query("SELECT id FROM profiles WHERE user_id = $1 AND topic = $2", [user.id, topic]))[0] as { id: string } | undefined; const effectiveTier = getEffectiveTier(user); if (!hasFounderAccess(user) && effectiveTier === "free" && !existing && await getProfileCount(user.id) >= 1) return { error: "limit_reached", limit: "profiles" }; const compiled = compileInterviewMarkdown(state as any, row.offering === "meos" ? getMeosGraph() : []); const portrait = JSON.stringify({ markdownFiles: compiled.allFiles }); const id = existing?.id ?? crypto.randomUUID(); await getDb().query(existing ? "UPDATE profiles SET offering = $1, tier = $2, state_json = $3, portrait_json = $4, updated_at = NOW() WHERE id = $5 AND user_id = $6" : "INSERT INTO profiles (id, user_id, topic, offering, tier, state_json, portrait_json) VALUES ($1, $2, $3, $4, $5, $6, $7)", existing ? [row.offering, user.tier, JSON.stringify(state), portrait, id, user.id] : [id, user.id, topic, row.offering, user.tier, JSON.stringify(state), portrait]); await getDb().query("DELETE FROM interview_drafts WHERE user_id = $1 AND offering = $2", [user.id, row.offering]); return { id, topic }; });
export const getInterviewDraft = createServerFn({ method: "GET" }).handler(async () => { const user = await requireUser(); const row = (await getDb().query("SELECT offering, topic, state_json, updated_at FROM interview_drafts WHERE user_id = $1 ORDER BY updated_at DESC LIMIT 1", [user.id]))[0] as { offering: string; topic: string; state_json: string; updated_at: string } | undefined; return row ? { ...row, state: JSON.parse(row.state_json) } : null; });
export const clearInterviewDraft = createServerFn({ method: "POST" }).handler(async () => { const user = await requireUser(); await getDb().query("DELETE FROM interview_drafts WHERE user_id = $1", [user.id]); return { success: true }; });
export const getOwnerMetrics = createServerFn({ method: "GET" }).handler(async () => { const user = await requireUser(); if (!isOwnerUser(user)) throw new Error("Not authorized."); return await queryOwnerMetrics(); });
export const getCurrentUser = createServerFn({ method: "GET" }).handler(async () => { await deleteExpiredSessions(); const token = getSessionTokenFromRequest(); if (!token) return null; const session = await getSessionByToken(token); if (!session) return null; if (new Date(session.expires_at) < new Date()) { await deleteSession(token); return null; } const user = await getUserById(session.user_id); if (!user) return null; const accessMode = getTestAccessMode(user); return { id: user.id, email: user.email, tier: getEffectiveTier(user), interviewCount: user.interview_count, isOwner: isOwnerUser(user), canTestAccess: isAccessTestUser(user), accessMode }; });
export const setTestAccessTier = createServerFn({ method: "POST" }).validator((data: unknown) => { const mode = (data as { mode?: string }).mode; if (mode !== "actual" && mode !== "founder" && mode !== "free" && mode !== "pro" && mode !== "lifetime") throw new Error("Unsupported test access mode."); return mode as TestAccessMode; }).handler(async ({ data }) => { const user = await requireUser(); if (!isAccessTestUser(user)) throw new Error("Not authorized."); setCookie(TEST_ACCESS_COOKIE, data, testAccessCookieOptions()); return { success: true, accessMode: data, tier: getEffectiveTier(user) }; });
export const trackInterview = createServerFn({ method: "POST" }).handler(async () => {
  const user = await requireUser();
  const effectiveTier = getEffectiveTier(user);
  if (hasFounderAccess(user)) return { interviewCount: user.interview_count, tier: effectiveTier, isOwner: isOwnerUser(user), accessMode: getTestAccessMode(user) };

  // Updating an already-saved profile is not a new interview. The continuation
  // flow autosaves its draft using the saved profile's topic, so we can identify
  // that case without weakening the one-profile free-tier boundary.
  const existingProfileUpdate = (await getDb().query(
    `SELECT p.id
       FROM interview_drafts d
       JOIN profiles p ON p.user_id = d.user_id AND p.topic = d.topic
      WHERE d.user_id = $1
      ORDER BY d.updated_at DESC
      LIMIT 1`,
    [user.id],
  ))[0] as { id: string } | undefined;
  if (existingProfileUpdate) {
    return { interviewCount: user.interview_count, tier: user.tier, isUpdate: true };
  }

  if (effectiveTier === "free" && user.interview_count >= 3) return { error: "limit_reached", limit: "interviews" };
  const newCount = await incrementInterviewCount(user.id);
  return { interviewCount: newCount, tier: effectiveTier };
});
export const fetchUserLimits = createServerFn({ method: "GET" }).handler(async () => { const user = await requireUser(); const limits = await getUserLimits(user.id); if (!limits) throw new Error("User not found."); const accessMode = getTestAccessMode(user); const effectiveTier = getEffectiveTier(user); const unlimited = accessMode === "founder" || effectiveTier !== "free"; return { ...limits, tier: effectiveTier, isOwner: isOwnerUser(user), canTestAccess: isAccessTestUser(user), accessMode, maxInterviews: unlimited ? Number.MAX_SAFE_INTEGER : 3, maxProfiles: unlimited ? Number.MAX_SAFE_INTEGER : 1 }; });
