import { useState } from "react";

export type FrameworkId = "astrology" | "humanDesign" | "enneagram" | "numerology" | "treeOfLife" | "bazi" | "iching" | "jungian" | "chakra";
export type Framework = { id: FrameworkId; label: string; description: string; birth: boolean };
export const FRAMEWORKS: Framework[] = [
  { id: "astrology", label: "Astrology (natal chart)", description: "Planetary placements as a reflective language.", birth: true },
  { id: "humanDesign", label: "Human Design", description: "A symbolic map for observing energy and decisions.", birth: true },
  { id: "enneagram", label: "Enneagram", description: "A lens for noticing motivations and patterns.", birth: false },
  { id: "numerology", label: "Numerology", description: "Meaning-making through numbers and names.", birth: false },
  { id: "treeOfLife", label: "Tree of Life (Kabbalah)", description: "A contemplative map of qualities and development.", birth: false },
  { id: "bazi", label: "Four Pillars / BaZi", description: "A traditional symbolic timing framework.", birth: true },
  { id: "iching", label: "I Ching", description: "A reflective lens for change and possibility.", birth: false },
  { id: "jungian", label: "Jungian archetypes", description: "Archetypes for exploring identity and story.", birth: false },
  { id: "chakra", label: "Chakra lens", description: "A symbolic vocabulary for embodied reflection.", birth: false },
];
const disclaimer = "Symbolic frameworks are optional lenses for self-reflection. ALVIRA does not present them as scientific, diagnostic, predictive, or deterministic. Your lived experience remains the highest validation layer.";
function Shell({ children, onBack }: { children: React.ReactNode; onBack?: () => void }) { return <div className="absolute inset-0 z-20 flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-lg max-h-[90%] overflow-y-auto rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-6 shadow-xl">{onBack && <button type="button" onClick={onBack} className="mb-4 font-mono text-xs text-gray-500 hover:text-human">← Back</button>}{children}</div></div>; }
const Button = ({ children, ...p }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button {...p} className="rounded-lg bg-human-dark dark:bg-human px-4 py-2.5 font-mono text-sm font-semibold text-white hover:bg-human-dark disabled:opacity-50">{children}</button>;
export function FrameworkSelector({ selected, onContinue }: { selected: FrameworkId[]; onContinue: (ids: FrameworkId[]) => void }) { const [chosen, setChosen] = useState<FrameworkId[]>(selected); return <Shell><h2 className="font-mono text-lg text-human-dark dark:text-human">&lt;frameworks /&gt; — Optional symbolic lenses</h2><div className="mt-5 space-y-2">{FRAMEWORKS.map(f => <label key={f.id} className="flex cursor-pointer gap-3 rounded-lg border border-gray-200 dark:border-gray-700 p-3"><input type="checkbox" checked={chosen.includes(f.id)} onChange={() => setChosen(x => x.includes(f.id) ? x.filter(id => id !== f.id) : [...x, f.id])} className="mt-1 accent-human" /><span><span className="block text-sm font-medium text-gray-900 dark:text-gray-100">{f.label}</span><span className="block text-xs text-gray-500 dark:text-gray-400">{f.description}</span></span></label>)}</div><p className="mt-5 text-xs leading-relaxed text-gray-500 dark:text-gray-400">{disclaimer}</p><div className="mt-5 flex justify-end"><Button onClick={() => onContinue(chosen)}>Continue</Button></div></Shell>; }
export function BirthDataForm({ initial, onContinue, onBack }: { initial?: { date?: string; time?: string; unknownTime?: boolean; location?: string }; onContinue: (data: object) => void; onBack: () => void }) { const [data, setData] = useState({ date: initial?.date || "", time: initial?.time || "", unknownTime: initial?.unknownTime || false, location: initial?.location || "" }); const set = (k: string, v: string | boolean) => setData(x => ({ ...x, [k]: v })); return <Shell onBack={onBack}><h2 className="font-mono text-lg text-human-dark dark:text-human">&lt;birth-data /&gt; — Optional details</h2><p className="mt-2 text-sm text-gray-600 dark:text-gray-400">Only used for selected frameworks that require birth information.</p><div className="mt-5 space-y-4"><label className="block text-xs font-mono text-gray-500">Birth date<input type="date" value={data.date} onChange={e => set("date", e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 p-2.5 text-sm dark:text-gray-100" /></label><label className="block text-xs font-mono text-gray-500">Birth time<input type="time" disabled={data.unknownTime} value={data.time} onChange={e => set("time", e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 p-2.5 text-sm dark:text-gray-100 disabled:opacity-50" /></label><label className="flex gap-2 text-xs text-gray-600 dark:text-gray-400"><input type="checkbox" checked={data.unknownTime} onChange={e => set("unknownTime", e.target.checked)} className="accent-human" /> I don't know the exact time</label><label className="block text-xs font-mono text-gray-500">Birth location (city + country)<input value={data.location} onChange={e => set("location", e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 p-2.5 text-sm dark:text-gray-100" /></label></div><div className="mt-5 flex justify-end"><Button onClick={() => onContinue(data)}>Continue</Button></div></Shell>; }
type Claim = { text: string; source: "user-supplied" | "inferred" };
export function ReviewPanel({ claims, onContinue, onBack }: { claims: Claim[]; onContinue: (results: object[]) => void; onBack: () => void }) { const [results, setResults] = useState<Record<number, { status: string; text?: string }>>({}); const act = (i: number, status: string) => setResults(x => ({ ...x, [i]: { status, text: x[i]?.text } })); return <Shell onBack={onBack}><h2 className="font-mono text-lg text-human-dark dark:text-human">&lt;review /&gt; — Check these reflections</h2><p className="mt-2 text-sm text-gray-600 dark:text-gray-400">Confirm, reject, revise, or defer each claim.</p><div className="mt-5 space-y-3">{claims.map((c, i) => <div key={i} className="rounded-lg border border-gray-200 dark:border-gray-700 p-3"><p className="text-sm text-gray-800 dark:text-gray-200">{c.text}</p><span className="font-mono text-[10px] text-human-dark dark:text-human">[{c.source}]</span><div className="mt-2 flex flex-wrap gap-1.5">{[["agree","✓ Agree"],["disagree","✗ Disagree"],["revise","✎ Revise"],["skip","⏭ Skip"]].map(([s,l]) => <button key={s} type="button" onClick={() => act(i,s)} className={`rounded border px-2 py-1 text-xs ${results[i]?.status === s ? "border-human text-human-dark" : "border-gray-300 dark:border-gray-600 text-gray-500"}`}>{l}</button>)}</div>{results[i]?.status === "revise" && <input autoFocus value={results[i]?.text || ""} onChange={e => setResults(x => ({ ...x, [i]: { ...x[i], text: e.target.value } }))} placeholder="Your revised statement" className="mt-2 w-full rounded border border-gray-300 dark:border-gray-700 bg-transparent p-2 text-sm dark:text-gray-100" />}</div>)}</div><div className="mt-5 flex justify-end"><Button onClick={() => onContinue(claims.map((c,i) => ({ ...c, ...(results[i] || { status: "skip" }) })))}>Continue</Button></div></Shell>; }
export function ValidationCard({ claims, onComplete, onBack }: { claims: Claim[]; onComplete: (note: string) => void; onBack: () => void }) { const [note, setNote] = useState(""); return <Shell onBack={onBack}><h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Here's what we've captured about you.</h2><p className="mt-2 text-sm text-gray-600 dark:text-gray-400">Take a moment to review.</p><div className="mt-5 space-y-2">{claims.slice(0, 8).map((c,i) => <div key={i} className="rounded border border-gray-200 dark:border-gray-700 p-3 text-sm text-gray-700 dark:text-gray-300"><span className="mr-2 text-human-dark">●</span>{c.text}<span className="ml-2 font-mono text-[10px] text-gray-400">high confidence</span></div>)}</div><textarea value={note} onChange={e => setNote(e.target.value)} placeholder="Anything missed or important to add?" className="mt-4 min-h-20 w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-transparent p-3 text-sm dark:text-gray-100" /><div className="mt-5 flex justify-end"><Button onClick={() => onComplete(note)}>Complete and compile ALVIRA Reflect</Button></div></Shell>; }
